### PR TITLE
Workaround build error(C3546) in vs2022(v17.11.2)

### PR DESCRIPTION
**Pull request by Y-way**

### CODE REVIEW

**Comment by LanderlYoung** [comment]
## For the error
Please leave detailed information about the error.
1. what is the cause
2. how to reproduce (a link on Compiler Explore would be appreciated)

## discussion
AFAIK, it seems to be a bug in MSVC
https://developercommunity.visualstudio.com/t/MSVC-compiler-bug---parameter-pack-expan/10419008?q=intellisense&sort=newest

If so, would upgrading Visual Studio be a workaround?

## further
The helper template `type_t` accepts the template parameter pack. It is better to change to:

```C++
template <typename... T>
inline internal::type_t<Local<Value>, decltype(&internal::TypeConverter<T>::toScript)...>
```

**Comment by Y-way** [comment]
cmake version is 3.29.3 and VisualStudio 2022 is the latest version on my computer.
step 1 clone ScriptX from remote.
step 2 cd path/to/ScriptX/test
step 3 do the command: cmake -S . -B .\build
step 4 cd the path/to/ScriptX/test/buld, and open the solution file ScriptXUnitTests.sln with vs2022
step 5 building the UnitTest project,it will occur error.

image

**Comment by LanderlYoung** [comment]
## Still, I recommend finding the real problem.
Please leave your MSVC version.

I created a minimal demo in Compiler Explorer, but couldn't reproduce this problem.

Here is the link: https://compiler-explorer.com/z/MTq4z9T6z

**Comment by Y-way** [comment]
> ## Still, I recommend finding the real problem.
> Please leave your MSVC version.
> 
> I created a minimal demo in Compiler Explorer, but couldn't reproduce this problem.
> 
> Here is the link: https://compiler-explorer.com/z/MTq4z9T6z


I have no idea.maybe it's a bug in the msvc compiler.

**Pull request merged**
